"""
this code is to resume the information generated by the clasification
"""

import os
import pandas as pd

# some constants
OUTPUT_FOLDER = "clasificacion"

# Create a list of folders in current directory
folders = [f for f in os.listdir(OUTPUT_FOLDER) if os.path.isdir(f"{OUTPUT_FOLDER}/{f}")]

# Keep only folders starting with "generated_imgs-"
folders = [f for f in folders if f.startswith("generated_imgs-")]

# Group the folders by string between "-" and "_"
groups = {}
for f in folders:
  key = f.split("-")[1].split("_")[0]
  if key not in groups:
    groups[key] = []
  groups[key].append(f)

# iterate over the groups
for key in groups:
  df = pd.DataFrame(columns=["source", "score", "prepreprocess", "preprocess", "algorithm"])
  for f in groups[key]:
    # retrieve from the file
    source = f.split("-")[1]
    # list all files starting with the file name imgSC
    files = [ff for ff in os.listdir(f"{OUTPUT_FOLDER}/{f}") if ff.startswith("imgSc")]
    # sort the files alphabetically
    files = sorted(files)
    # iterate over the files
    for ff in files[-2:]:
      # retrieve the score between "imgSC" and "_"
      score = float(ff.split("_")[0][5:])/100
      # retrieve the source
      prepreprocess = ff.split("_")[1]
      # retrieve the preprocess
      preprocess = ff.split("_")[2]
      # retrieve the algorithm
      algorithm = "_".join(ff.split("_")[3:]).split(".")[0]
      # append the row
      data = {"source":source, "score":score, "prepreprocess":prepreprocess, "preprocess":preprocess, "algorithm":algorithm}
      df.loc[len(df)] = data
    
  # sort the dataframe by score
  df = df.sort_values(by="score", ascending=False)
  # show the dataframe
  print(f"\n\t{source}")
  print(df)
